# Generated by Django 2.1.2 on 2018-12-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20181203_0928'),
        ('articles', '0002_auto_20181216_1424'),
    ]

    operations = [
    ]
