# Generated by Django 2.1.2 on 2018-11-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20181114_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
